version: '3'

services:
  db:
    build: ./docker/db
    container_name: django.db
    # If container gets file operation error, rebuild container and add command option.
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    volumes:
    # Data mounted directory (expressly)
      - ./db/data:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - TZ='Asia/Tokyo'
    networks:
      - back

  web:
    build: ./docker/web
    container_name: django.web
    command: uwsgi --socket :8001 --module mysite.wsgi
    # If response gets 502 error(Permissiondenied), try chmod option.
    # command: uwsgi --socket :8001 --module mysite.wsgi --chmod-socket=666
    # command: uwsgi --socket :8001 --module mysite.wsgi --chmod-socket=664
    volumes:
      - ./:/code
    expose:
      - "8001"
    depends_on:
      - db
    networks:
      - front
      - back

  nginx:
    build: ./docker/nginx
    container_name: django.nginx
    depends_on:
      - web
    ports:
      - "8000:8000"
    networks:
      - front

networks:
  front:
    driver: bridge
  back:
    driver: bridge