version: '3'

services:
  db:
    build: ./docker/db
    container_name: django.db
    # If container gets file operation error, rebuild container and add command option.
    command: --innodb-use-native-aio=0
    volumes:
    # Data mounted directory (expressly)
      - ./docker/db/data:/var/lib/mysql
    expose:
      - "3306"
    env_file: .env
    networks:
      - back

  web:
    build: ./docker/web
    container_name: django.web
    command: uwsgi --socket :8001 --module mysite.wsgi
    # If response gets 502 error(Permissiondenied), try chmod option.
    # command: uwsgi --socket :8001 --module mysite.wsgi --chmod-socket=666
    # command: uwsgi --socket :8001 --module mysite.wsgi --chmod-socket=664
    volumes:
      - ./:/code
    expose:
      - "8001"
    depends_on:
      - db
    networks:
      - front
      - back

  nginx:
    build: ./docker/nginx
    container_name: django.nginx
    volumes:
      - ./static:/static
    depends_on:
      - web
    ports:
      - "8000:8000"
    networks:
      - front

  node:
    build: ./docker/node
    container_name: django.npm
    volumes:
      - ./docker/node:/home/node/configuration
      - ./static:/home/node/static
      - ./apps/frontEnd:/home/node/apps/frontEnd
      - ./docker/node/webpack.config.js:/home/node/webpack.config.js
      - node_modules:/home/node/node_modules
    tty: true

networks:
  front:
    driver: bridge
  back:
    driver: bridge

volumes:
  node_modules:
    driver: local
